playslave
---------

+playslave+ is an attempt at making a small audio playback wrapper on top of 
_ffmpeg_ and _portaudio_ that can be controlled through stdout and stdin with a
simple protocol.

It might end up being the bottom rung of a playback system someday.  Who knows.

It is written in C99 against POSIX.1-2008, and should compile on any recent 
nix-like.

Usage
~~~~~

More functionality to be added when needed.

- Command argument is the libao ID to output to.
- +playslave+ starts in the *EJECTED* state.
- +load+ _file_ - loads _file_, stops any current playback, places
  +playslave+ in *STOPPED* state.
- +play+ - plays file when in *STOPPED* state, moves +playslave+ to
  *PLAYING* state.
- +ejct+ - ejects file when in *STOPPED* or *PLAYING* state.
- +quit+ - exits +playslave+.
- +seek+ _time_ - seeks to _time_ microseconds into the current stream when
  *STOPPED* or *PLAYING*.  If _time_ ends in `s` or `sec`, however, the
  number will be taken as seconds.

Known issues
~~~~~~~~~~~~

- STOPping currently drops a frame or two on resumption
- SEEKing too far throws an internal error
- No real use as of yet

Acknowledgments
~~~~~~~~~~~~~~~

A lot of the audio bits of this were salvaged from example code, most notably 
http://blinkingblip.wordpress.com/2011/10/08/decoding-and-playing-an-audio-stream-using-libavcodec-libavformat-and-libao/
and some other sources.

Licence
~~~~~~~

+playslave+ is distributed under the terms of the GNU General Public License,
version 2.  See +COPYING+ for details.

_ffmpeg_ and _portaudio_ are used by +playslave+; they are also available under
the terms of the GPLv2 and MIT licences respectively.

Parts of _portaudio_ are included in +/src/contrib+; the _portaudio_ license
is available in +LICENSE.portaudio+.
